import type { FullConfig } from './types.js'

export const defaultConfig: FullConfig = {
  generic: {
    attackRange: 3.0,
    viewDistance: 128,
    tooCloseRange: 2.5,
    enemyReach: 3.0,
    hitThroughWalls: false,
    missChance: 0,
    respectIframes: false,
  },
  cps: {
    max: 18,
    engagingRange: { min: 12, max: 16 },
    comboRange: { min: 15, max: 18 },
  },
  wTap: {
    enabled: true,
    everyHits: { min: 1, max: 2 },
    iframeTicks: 10,
    releaseMsRange: { min: 10, max: 25 },
    reSprintMsRange: { min: 8, max: 20 },
  },
  blockHit: {
    enabled: true,
    everyHits: { min: 1, max: 2 },
    holdDuration: { min: 80, max: 160 },
    postDuration: { min: 40, max: 100 },
  },
  strafe: {
    enabled: true,
    mode: 'predictive',
    durationJitter: { min: 8, max: 20 },
    pauseProbability: 0.06,
    pauseDurationTicks: { min: 2, max: 6 },
    circleSwitchEnabled: true,
    circleSwitchIntervalHits: { min: 2, max: 4 },
    predictiveNoiseFactor: 0.15,
  },
  rotate: {
    enabled: true,
    smooth: true,
    lookAtHidden: true,
    mode: 'constant',
    microSaccadeAmplitude: 0.018,
    microSaccadeFrequency: 0.25,
    lookAwayProbability: 0.004,
    lookAwayDurationTicks: { min: 1, max: 3 },
    overshootEnabled: true,
    overshootAmplitude: 0.008,
    overshootRecoveryFactor: 0.65,
    fittsBias: 0.5,
  },
  critical: {
    enabled: false,
    mode: 'hop',
    attemptRange: 2.5,
    reactionEnabled: true,
    maxWaitTicks: 5,
    maxWaitDistance: 5,
    maxPreemptiveTicks: 1,
  },
  shield: {
    enabled: true,
    mode: 'legit',
    disableEnabled: true,
    disableMode: 'single',
  },
  follow: {
    mode: 'standard',
    distance: 3,
    predictive: true,
    predictTicks: 4,
  },
  bow: {
    enabled: true,
    preferOverFireball: true,
    aimBackend: 'bow-aiming',
    leadIterations: 8,
    bridgeKnockbackEnabled: true,
  },
  fireball: {
    enabled: true,
    deflectRange: 5,
    deflectClickInterval: { min: 40, max: 80 },
  },
  pearl: {
    enabled: true,
    aggressiveRange: 16,
    throwHuntdown: true,
    defensiveEnabled: true,
    voidFallThreshold: 3,
    safeLandingSearchRadius: 12,
  },
  dodge: {
    enabled: true,
    reactionDelayMs: { min: 40, max: 90 },
    jumpEnabled: true,
    deflectIntervalMs: { min: 40, max: 80 },
  },
  gap: {
    enabled: true,
    healthThreshold: 14,
    eatDuringCombat: true,
    shieldWhileEating: true,
  },
  lowHealth: {
    threshold: 12,
    extendedBlockEnabled: true,
    blockHoldDuration: { min: 300, max: 600 },
    preferBlockOverAttack: false,
  },
  multiEnemy: {
    enabled: true,
    assistTeammates: true,
  },
  jumpBoost: {
    enabled: true,
    useForHeightAdvantage: true,
    useForEscape: true,
    useForTowering: false,
  },
  humanization: {
    reactionDelay: { min: 40, max: 90 },
    rotateSmoothFactor: 0.45,
    movementNoise: 0.03,
    attackJitterMs: { min: 0, max: 25 },
    cpsVarianceFactor: 0.12,
    postHitPauseProbability: 0.08,
    postHitPauseDurationMs: { min: 30, max: 90 },
    strafeJitterAmplitude: 0.04,
    strafeJitterFrequency: 0.18,
    focusLapseFrequency: 0.01,
    focusLapseDurationTicks: { min: 1, max: 3 },
    sprintToggleNoiseProbability: 0.015,
    jumpTimingVarianceTicks: 1,
    eyeHeightVarianceFactor: 0.015,
    mouseAccelerationFactor: 0.12,
    angleCorrectionThreshold: 0.04,
    angleCorrectionSpeed: 0.7,
    wristFatigueEnabled: true,
    wristFatigueCpsReduction: 0.08,
    clickReleaseDelayMs: { min: 20, max: 65 },
    naturalDecelerationEnabled: true,
    framerateSim: { min: 58, max: 65 },
    subTickMouseMovements: true,
  },
  adaptation: {
    enabled: true,
    minDataPoints: 8,
  },
  decisionEngine: {
    enabled: true,
    updateIntervalTicks: 1,
    aggressionBias: 0.78,
    defensiveBias: 0.2,
    retreatHealthThreshold: 0.25,
  },
  behaviorBlend: {
    enabled: true,
    smoothingFactor: 0.22,
    strafeBaseWeight: 0.75,
    hitSelectBaseWeight: 0.88,
    retreatBaseWeight: 0.08,
  },
  prediction: {
    enabled: true,
    velocityHistoryLen: 12,
    positionLeadTicks: 4,
    attackPatternMemoryLen: 30,
    movementEntropyWindow: 20,
  },
  fatigue: {
    enabled: true,
    onsetTicks: 400,
    cpsPenaltyFactor: 0.88,
    strafeFrequencyPenaltyFactor: 0.6,
    recoveryTicks: 50,
  },
  blockTrap: {
    enabled: true,
    triggerRange: 3.5,
    cooldownTicks: 60,
    twoBlockEnabled: true,
    twoBlockVelocityThreshold: 0.08,
    pillarEnabled: true,
    pillarMovingProbability: 0.55,
    pillarStationaryProbability: 0.05,
    placementJitterTicks: { min: 0, max: 1 },
    baseScore: 0.05,
    minTriggerScore: 0.5,
    comboEscapeTickWindow: 12,
    comboEscapeScoreBonus: 0.65,
    velocityNormFactor: 0.25,
    velocityScoreWeight: 0.25,
    healthPressureThreshold: 12,
    healthPressureWeight: 0.2,
    proximityScoreWeight: 0.12,
  },
  teammates: [],
}
